### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by whoot**
Since I had a really hard time installing Belati I would love to see the following requirements in the readme.

During installation I made the experience that it is better to install the dependencies directly from github instead of using pip. So there are no error messages and the installation runs smoothly.

### CODE REVIEW

**Comment by aancw** [comment]
Hey, can you provide more details about error?

**Comment by whoot** [comment]
All errors came from pip, when I tried to download and install dependencies. They could be resolved by download the tools directly from github. 

Update: Weird... I tried it again in a clean environment and the only thing i had to do was to install the exiftool (sudo apt-get install exiftool) and it worked. 
I changed the readme according to this.

**Comment by aancw** [comment]
Yes, it's because pyexifinfo need exiftool. Reference to this issue:
https://github.com/aancw/Belati/issues/15 and this https://github.com/aancw/Belati/issues/21 . Me and my friend @Chan9390 submitted to pyexifinfo repo but no response from dev ref to this issue https://github.com/guinslym/pyexifinfo/issues/9

Thanks for your support, but i'm making Belati for universal environment. Not just for debian/ubuntu with apt-get support. I think i will keep readme as it is. If you don't mind, you can still PR with exiftool installation instruction for debian with new section in readme file.

**Comment by whoot** [comment]
The reason for my submission was to ease the installation process for everyone out there.
Like I said, I had a hard time setting everything up and had so search through the issues to find the solution(s). Maybe it would be sufficient keeping it in a new section. 

EDIT: changed the readme according to your suggestion.

**Comment by aancw** [comment]
I understand, but it's better to make a new section like that. Thank you very much <3

**Pull request merged**
