### PR TITLE
Fix unexpected termination when Google is blocking requests, issue #7

### PR DESCRIPTION
**Pull request by melizeche**
Probably not the best fix but it's a quick hack so Belati can finish executing

### CODE REVIEW

**Comment by aancw** [comment]
Maybe the best solution is use try catch :)

But thanks for your patch!

**Comment by aancw** [comment]
I will update in the next release :D

**Comment by r3k2** [comment]
@aancw Melizeche is a friend from Uruguay also in the hispagatos community chat

**Comment by aancw** [comment]
@ChrisFernandez Ah ok. I see you are following him on twitter. I will online mattermost tomorrow :)

**Comment by aancw** [comment]
Implemented in the next release.
Thanks!

**Pull request closed without merging**
