### PR TITLE
Add Django==1.11.6

### PR DESCRIPTION
**Pull request by irwandi**
since it using python 2.x, need to force some requirement to "fixed" Version. 

Will Add More Later. :)

### CODE REVIEW

**Comment by aancw** [comment]
Thanks!

**Comment by aancw** [comment]
Hi @irwandi, i think i need to fix dependency checker parser first for lib==version

**Comment by irwandi** [comment]
I Will Build a Clean VM And Test it Again.

**Comment by aancw** [comment]
For temporary fix, i need to revert this change while developing new parser. Please wait :)

**Comment by irwandi** [comment]
Sure. Thank You.

**Comment by aancw** [comment]
Done~

So, for the next release it will compare module version, check installed module and more accurate dependencies checker. Thanks.

**Comment by aancw** [comment]
belati-depcheck-1
belati-depcheck-2


In the 0.2.4 version, Belati will using command line shell instead of command line arguments :)

**Pull request merged**
